version: "3.9"

secrets:
  db_user:
    file: ./db_user.txt
  db_password:
    file: ./db_password.txt

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    secrets:
      - db_user
      - db_password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.1-apache
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    secrets:
      - db_user
      - db_password
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER_FILE=/run/secrets/db_user
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WORDPRESS_DB_NAME=wordpress
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
     - ./nginx/devconf:/etc/nginx/conf.d
     - ./certbot/conf:/etc/nginx/ssl
     - ./certbot/data:/var/www/html


volumes:
  db_data: {}
  wordpress_data: {}
